tools:
  xray_path: "/usr/local/share/xray/xray_linux_amd64"   
  xray_config_dir: "/usr/local/share/xray"            
defaults:
  mode: "normal"
  timeout: 3600
  report_dir: "reports"
flags:
  normal: ["--basic-crawler"]
  silent: ["--passive"]
  brutal: ["--browser-crawler","--level","high"]
